components:
  schemas:
    ErrorResponse:
      properties:
        code:
          example: 400
          type: integer
        message:
          example: Invalid input
          type: string
      type: object
    Teacher:
      properties:
        email:
          example: johndoe@example.com
          format: email
          type: string
        firstName:
          example: John
          type: string
        lastName:
          example: Doe
          type: string
        subject:
          example: Mathematics
          type: string
      required:
      - firstName
      - lastName
      - email
      - subject
      type: object
    TeacherResponse:
      properties:
        email:
          example: johndoe@example.com
          format: email
          type: string
        firstName:
          example: John
          type: string
        id:
          example: 1
          type: integer
        lastName:
          example: Doe
          type: string
        subject:
          example: Mathematics
          type: string
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://www.example.com/support
  description: API for managing teacher records, including creation, retrieval, updating, and deletion of teacher information.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Teacher Management API
  version: 1.0.0
openapi: 3.0.3
paths:
  /teachers:
    post:
      operationId: createTeacher
      requestBody:
        content:
          application/json:
            examples:
              example1:
                value:
                  email: johndoe@example.com
                  firstName: John
                  lastName: Doe
                  subject: Mathematics
            schema:
              $ref: '#/components/schemas/Teacher'
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                example1:
                  value:
                    email: johndoe@example.com
                    firstName: John
                    id: 1
                    lastName: Doe
                    subject: Mathematics
              schema:
                $ref: '#/components/schemas/TeacherResponse'
          description: Teacher created successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid input
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error
      summary: Create a new teacher
      tags:
      - Teachers
  /teachers/{id}:
    delete:
      operationId: deleteTeacher
      parameters:
      - description: ID of the teacher to delete
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Teacher deleted successfully
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Teacher not found
      summary: Delete a teacher by ID
      tags:
      - Teachers
    get:
      operationId: getTeacherById
      parameters:
      - description: ID of the teacher to retrieve
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              examples:
                example1:
                  value:
                    email: johndoe@example.com
                    firstName: John
                    id: 1
                    lastName: Doe
                    subject: Mathematics
              schema:
                $ref: '#/components/schemas/TeacherResponse'
          description: Teacher retrieved successfully
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Teacher not found
      summary: Get a teacher by ID
      tags:
      - Teachers
    put:
      operationId: updateTeacher
      parameters:
      - description: ID of the teacher to update
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherResponse'
          description: Teacher updated successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid input
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Teacher not found
      summary: Update a teacher by ID
      tags:
      - Teachers
security:
- BearerAuth: []
servers:
- description: Production server
  url: https://api.example.com/v1
tags:
- description: Operations related to teachers
  name: Teachers
